service: user-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  versionFunctions: false
  stage: "dev"
  region: us-east-1
  httpApi:
    cors: true

functions:
  Signup:
    handler: app/handler.Signup
    events:
      - httpApi:
          path: /Signup
          method: post
  Login:
    handler: app/handler.Login
    events:
      - httpApi:
          path: /Login
          method: post
plugins:
  - serverless-offline
  - serverless-plugin-typescript
